site_name: Storebrowse for Citrix Workspace app 1808 for Windows
site_description: Commmand-line reference for Storebrowse for Citrix Workspace app 1808 for Windows
theme_dir: material
extra_css:
  - 'assets/stylesheets/extra.css'
repo_url:
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      anchorlink: True

pages:
- Home: index.md
- Storebrowse Command Usage: command-usage.md
- Single Sign-on Support of NetScaler Gateway: single-sign-on-support.md
- Known Limitations: known-limitations.md

