site_name: Storebrowse for Citrix Workspace app for Windows
site_description: Commmand-line reference for Storebrowse for Citrix Workspace app for Windows
theme_dir: material
extra_css:
  - 'assets/stylesheets/extra.css'
repo_url:
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      anchorlink: True

pages:
- Home: index.md

